CREATE TABLE IF NOT EXISTS t_daily_production_planning_config (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  line_key VARCHAR(32) NOT NULL,
  fdate DATE NOT NULL,
  fshift VARCHAR(16) NOT NULL,
  fgroup VARCHAR(16) NOT NULL,
  ftt DECIMAL(8,3) NOT NULL DEFAULT 0,
  foee DECIMAL(5,2) NOT NULL DEFAULT 90,
  fratio VARCHAR(20) NOT NULL DEFAULT '1:1',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY daily_planning_config_unique (line_key, fdate, fshift, fgroup)
);
