ALTER TABLE t_daily_production_planning_slot
  ADD COLUMN IF NOT EXISTS ftt DECIMAL(8,3) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS foee DECIMAL(5,2) NOT NULL DEFAULT 90,
  ADD COLUMN IF NOT EXISTS fratio VARCHAR(20) NOT NULL DEFAULT '1:1';

DROP TABLE IF EXISTS t_daily_production_planning_config;
